name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [6.x, 8.x, 10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2-beta
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install --no-save
    - name: Test
      run: |
        tmp=$(mktemp --directory)
        bash -O dotglob -O extglob -c 'mv !(node_modules|test.js) "$1"/' bash "$tmp"
        pack=$(npm pack "$tmp")
        tar --strip-components=1 -x -v -f "$pack"
        node test
